<template>
  <div id="app">
      <v-footer id="v-footer" dark padless inset elevation="5" v-show="isScrollDown">
        <v-card id="v-card" flat tile class="lighten-1 white--text text-center">
          <v-card-text class="pa-2">
            <v-btn v-for="icon in footerIcons" :key="icon" class="mx-4 white--text" icon>
              <v-icon size="24px">{{ icon }}</v-icon>
            </v-btn>
          </v-card-text>
          <!--        <v-card-text class="white&#45;&#45;text pa-2">-->
          <!--          this website was generated by Yiming Liao-->
          <!--        </v-card-text>-->
          <v-divider></v-divider>
          <v-card-text class="white--text pa-2">
            {{ new Date().getFullYear() }} — <strong>yonmineliao@gmail.com</strong>
          </v-card-text>
        </v-card>
      </v-footer>
  </div>
</template>

<script>
export default {
  name: "TailBar",
  data: () => ({
    isScrollDown: false,
    footerIcons: [
      'mdi-facebook',
      'mdi-facebook-messenger',
      'mdi-facebook-workplace',
      'mdi-google-plus',
      'mdi-twitter',
      'mdi-linkedin',
      'mdi-instagram',
      'mdi-youtube',
      'mdi-reddit',
      'mdi-snapchat',
      'mdi-twitch',
    ],
  }),
  mounted() {
    window.addEventListener("scroll", () => {// 滚动事件
      let html = document.documentElement
      if (html.scrollTop >= 100) {//当滚动高度大于等于100返回顶部出现
        this.isScrollDown = true
      } else {
        this.isScrollDown = false
      }
    })
  },
  methods:{

  }
}
</script>

<style scoped>

#v-footer {
  width: 100%;
  flex-direction: column;
  align-items: stretch;
}

#v-card {
  background: linear-gradient(60deg, #41B883, #1166d5);
}

</style>
